### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pexcn** [openwrt-dev/openwrt-feeds#1]
- [x] luci-app-shadowsocks
- [x] openwrt-dist-luci
- [x] openwrt-chinadns
- [x] openwrt-dns-forwarder
- [x] openwrt-shadowsocks
- [ ] adkill
- [ ] adblock
- [ ] pdnsd
- [ ] axel
- [ ] aria2
- [ ] aria2-webui
